### ISSUE TITLE
Databinding package

### ISSUE THREAD

**Issue by drewgash** [Mindjet/MyGallery#1]
Is there a _databinding_ package missing?

**Comment by Mindjet** [comment]
Nice question. As far as I know, the package `databinding`  is already integrated since Android Studio 1.3 and gradle 1.5.0-alpha1.

In order to introduce `databinding`, all you need to do is declare it in the `build.gradle` of your module like below.

```gradle
android {
  ....
  dataBinding {
      enabled =true
  }
}
```

Hope it's useful for you.
